"""Remove timestamp fields from User and UserWrongAnswer models

Revision ID: 361787b386d9
Revises: d0aa691581c4
Create Date: 2023-10-15 18:35:52.662742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '361787b386d9'
down_revision = 'd0aa691581c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('users', 'created_at')
    except Exception:
        pass
        
    try:
        op.drop_column('users', 'updated_at')
    except Exception:
        pass
        
    try:
        op.drop_column('user_wrong_answers', 'created_at')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_wrong_answers', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ### 